# Store file in your working directory
# and then read into a data frame. 

brexit_data <- read.csv("data_brexit_referendum.csv")
head(brexit_data)

#What data type is this file?
class(brexit_data)

# Lets look at the structure of the file
str(brexit_data)

# --------------------------------------------------------------------------------------
# Dealing with missing data
# --------------------------------------------------------------------------------------

# The original data has missing values
# represented by the number "-1"
# We need to search for these and replace them

# Check for values in "Leave" column where
# vlaue = -1
sum(brexit_data$Leave[brexit_data$Leave == -1])

# replace this with NA
brexit_data$Leave[brexit_data$Leave == -1] <- NA

# Verify that the replace happened
sum(brexit_data$Leave[brexit_data$Leave == -1])

# View the records with NA
na_records <- brexit_data[!complete.cases(brexit_data),]
na_records

# Same count as when values were -1
nrow(na_records)

install.packages("mice")
library(mice)
# 15 records have missing NI address
# 10 have missing type
md.pattern(brexit_data)

library(VIM)

# Looks like the missing values are all in this 1 column
# for "Leave". We're not going to use it for now
# so we'll leave it as it is
missing_values <- aggr(brexit_data, prop = FALSE, numbers = TRUE)

# --------------------------------------------------------------------------------------
# Describing the brexit data - do this for CA1
# --------------------------------------------------------------------------------------

# Lets look at the proportion of voters who
# are in favour of leaving the E.U.
# I'm creating a new variable to store this information in
# The focus of this dataset is brexit voters and their
# various attributes

brexit_data$Proportion <- brexit_data$Leave / brexit_data$NVotes
brexit_data$Proportion

# Store remain or leave in the Vote variable
brexit_data$Vote[brexit_data$Proportion <= 0.5] <- "Remain"
brexit_data$Vote[brexit_data$Proportion > 0.5] <- "Leave"
brexit_data$Vote

attach(brexit_data)
# Note that we still need to refer to the full path to the variable for
# part of the statement

# Need to convert to character from factor before we can convert the variable

brexit_data$RegionName <- as.character(RegionName)
str(brexit_data)
brexit_data$RegionName[RegionName == "London"] <- "L" # Check that this has happened
brexit_data$RegionName[RegionName == "North West"] <- "NW" # do this to make charts look better
brexit_data$RegionName[RegionName == "North East"] <- "NE" 
brexit_data$RegionName[RegionName == "South West"] <- "SW" 
brexit_data$RegionName[RegionName == "South East"] <- "SE" 
brexit_data$RegionName[RegionName == "East Midlands"] <- "EM" 
brexit_data$RegionName[RegionName == "West Midlands"] <- "WM" 
brexit_data$RegionName[RegionName == "East of England"] <- "EE" 
brexit_data$RegionName[RegionName == "Yorkshire and The Humber"] <- "Y" 

# Now we have a new variable of interest called proportion
# and we will now focus on this variable

# Lets view the summary of the data

# We can see that this shows relevant summaries of the data
# and it is tailored for each data type
summary(brexit_data)

# We're not able to directly reference this data because some is non-numeric
# and does not contai nwhat we want to view such as minimum, first quartile, median, mean, third quartile
# but we can use sapply() and check whether each data variable is a numeric variable or not
# eg to check whether proportion is a numeric value or not
is.numeric(brexit_data$Proportion)
is.numeric(brexit_data$RegionName)

# Use double-tab for structure of sapply()
numeric_variable_list <- sapply(brexit_data, is.numeric)
numeric_variable_list

# change ID in numeric_variable_list to false to get rid of ID column
numeric_variable_list["ID"] <- FALSE

# We can use this logic to create a subset of the data
numerical_data <- brexit_data[numeric_variable_list]
colnames(numerical_data)

?cbind
# combine objects by columns and rows
# so we can use this function to create
# a dataset of the lapply() output
  # this code allows us to convert a summery into a dataframe
# do.call() allows us to apply cbind() to each element generated by lapply
numerical_summary <- do.call(cbind, lapply(numerical_data, summary))
numerical_summary

# summary variables as columns and variable names as rows
alt_numerical_summary <- do.call(rbind, lapply(numerical_data, summary))
alt_numerical_summary

# specific values such as max proportion value
# of those who voted to leave
# proportion = leave / no of votes in ward
maxProp <- numerical_summary["Max.", "Proportion"] # to extract specific pieces of data from the dataframe
maxProp
# minimum value in Deprived column
minDep <- numerical_summary["Min.", "Deprived"]
minDep
# min value in proportion column
minProp <- numerical_summary["Min.", "Proportion"]
minProp
rangeProp <- c(minProp, maxProp)
rangeProp
# range of values in proportion 
rangeP <- maxProp - minProp
rangeP

# use NoQuals, Proportion, AdultMeanAge, L4QualsPlus, RegionName
# into display_variables

display_variables <- c("NoQuals", "Proportion", "AdultMeanAge", "L4Quals_plus", "RegionName")
display_variables

# get the row that holds the max value in Proportion column from the brexit_data DF
brexit_data[which.max(brexit_data$Proportion), display_variables]
# get the row that holds the min value in Proportion column from the brexit DF
brexit_data[which.min(brexit_data$Proportion), display_variables]
# creates a table of the proportions of voters from each region
prop.table(table(brexit_data$RegionName))

# plot the proportions of voters from each region
barplot(height = prop.table(table(brexit_data$RegionName)), main = "Vote proportion", 
        ylab = "Frequency",
        xlab = "Region",
        col = "blue")

# create a plot to show differences in qualifications
# show charts side by side
# use mfrow

# use this as an example
hist(brexit_data$MeanAge, 
     main = "Histogram for mean adult age (years)", 
     col = "blue",
     ylab = "Frequency",
     xlab = "MeanAge")

opar <- par(no.readonly = TRUE) # records current settings for plots
par(mfrow = c(1,2)) # plot side by side

hist(brexit_data$NoQuals, 
     main = "Histogram for no qualifications", 
     col = "blue",
     ylab = "Frequency",
     xlab = "% of residents with no qualifications") # 15-20% have no qualifications


hist(brexit_data$L4Quals_plus , 
     main = "Histogram for level 4+ qualifications", 
     col = "blue",
     ylab = "Frequency",
     xlab = "% of residents with level 4+ qualifications")

# reset opar
par(opar)

plot(x = brexit_data$NoQuals, 
     y = brexit_data$AdultMeanAge, 
     xlab = "% of people in each ward with No quals", 
     ylab = "Adult mean age")

plot(x = brexit_data$L4Quals_plus, 
     y = brexit_data$AdultMeanAge, 
     xlab = "% of people in each ward with L4+ quals", 
     ylab = "Adult mean age")

# examine the data in more detail
# do this in CAs as a starting point 
# this identifies correlations between variables
# once correlations are identified, do another plot on that
# high level view of all the data. 
# bottom left - proportion on y axis, adultmeanage on x
# top right - adultmeanage on y axis, proportion on x
variables_of_interest <- c("AdultMeanAge", 
                           "Owned", 
                           "NoQuals", 
                           "L4Quals_plus", 
                           "Unemp",
                           "HigherOccup",
                           "Deprived",
                           "Proportion")
# 
pairs(brexit_data[variables_of_interest])

# shows pos and neg correlations data in the data
# when building a neural network you need correlations first 
# to identify related variables
install.packages("corrplot")
library(corrplot)
corrplot(corr = cor(numerical_data),
         t1.col = "Black",
         method = "number",
         t1.cex = 0.5)

# education and ethnicity influence how people voted
# young educated people voted to stay

# next step is to split data up - dump irrelivent data
# just keep meaningful data

# age 44 and below
brexit_data$under45 <- (Age_18to19+
                        Age_20to24+
                        Age_25to29+
                        Age_30to44)
# age 45 and above
brexit_data$over45 <- (Age_45to59 +
                         Age_60to64 +
                         Age_65to74 +
                         Age_75to84 +
                         Age_85to89 +
                         Age_90plus )
head(brexit_data)
